name: CI

on: push

jobs:
  build:
    name: build review pdf
    runs-on: ubuntu-latest
    container: docker://kauplan/review2.5

    steps:
    - uses: docker://pandoc/latex:2.9
    - name: install pandoc2review
      run: gem install pandoc2review
    - uses: actions/checkout@master
    - name: pandoc2review
      run: |
          cd articles
          pandoc2review test.md > ../contents/test.re
    - name: ls
      run: ls
    - name: pwd
      run: pwd
    - name: cat
      run: cat ./contents/test.re  
    - name: build pdf
      run: rake pdf
    - uses: actions/upload-artifact@master
      with:
        name: build-pdf
        path: ./techbook.pdf